In [2]:
import os
os.getcwd()

'c:\\Users\\legar\\Documents\\JEHDA\\Fullstack\\Projets\\Happiness\\notebooks'

In [3]:
import pandas as pd

whr = pd.read_excel("../data/raw/WHR25_Data_Figure_2.1v3.xlsx")
wb = pd.read_csv("../data/raw/world_bank_data_2025.csv")

In [8]:
whr.head()

,Year,Rank,Country name,Life evaluation (3-year average),Lower whisker,Upper whisker,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,2024,147,Afghanistan,1.364,1.301,1.427,0.649,0.0,0.155,0.0,0.075,0.135,0.348
1,2023,143,Afghanistan,1.721,1.667,1.775,0.628,0.0,0.242,0.0,0.091,0.088,0.672
2,2022,137,Afghanistan,1.859,1.795,1.923,0.645,0.0,0.087,0.0,0.093,0.059,0.976
3,2021,146,Afghanistan,2.404,2.339,2.469,0.758,0.0,0.289,0.0,0.089,0.005,1.263
4,2020,150,Afghanistan,2.523,2.449,2.596,0.370,0.0,0.126,0.0,0.122,0.010,1.895

In [10]:
display(whr.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 13 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Year                                        1969 non-null   int64
 1   Rank                                        1969 non-null   int64
 2   Country name                                1969 non-null   object
 3   Life evaluation (3-year average)            1969 non-null   float64
 4   Lower whisker                               875 non-null    float64
 5   Upper whisker                               875 non-null    float64
 6   Explained by: Log GDP per capita            872 non-null    float64
 7   Explained by: Social support                872 non-null    float64
 8   Explained by: Healthy life expectancy       870 non-null    float64
 9   Explained by: Freedom to make life choices  871 non-null    float64
 10  Explained by: Generosity                    872 non-null    float64
 11  Explained by: Perceptions of corruption     871 non-null    float64
 12  Dystopia + residual                         868 non-null    float64
dtypes: float64(10), int64(2), object(1)
memory usage: 200.1+ KB

None

In [6]:
whr.columns

Index(['Year', 'Rank', 'Country name', 'Life evaluation (3-year average)',
       'Lower whisker', 'Upper whisker', 'Explained by: Log GDP per capita',
       'Explained by: Social support', 'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual'],
      dtype='object')

In [11]:
wb.head()

,country_name,country_id,year,Inflation (CPI %),GDP (Current USD),GDP per Capita (Current USD),Unemployment Rate (%),"Interest Rate (Real, %)","Inflation (GDP Deflator, %)",GDP Growth (% Annual),Current Account Balance (% GDP),Government Expense (% of GDP),Government Revenue (% of GDP),Tax Revenue (% of GDP),Gross National Income (USD),Public Debt (% of GDP)
0,Aruba,aw,2010,2.078141,2.453597e+09,24093.140151,NaN,11.666131,-1.223407,-2.733457,-18.752537,NaN,NaN,NaN,2.313385e+09,NaN
1,Aruba,aw,2011,4.316297,2.637859e+09,25712.384302,NaN,4.801974,4.005674,3.369237,-9.877656,NaN,NaN,NaN,2.391841e+09,NaN
2,Aruba,aw,2012,0.627472,2.615208e+09,25119.665545,NaN,8.200875,0.184033,-1.040800,3.473451,NaN,NaN,NaN,2.499118e+09,NaN
3,Aruba,aw,2013,-2.372065,2.727850e+09,25813.576727,NaN,10.709709,-1.995948,6.431483,-11.813206,NaN,NaN,NaN,2.563517e+09,NaN
4,Aruba,aw,2014,0.421441,2.790850e+09,26129.839062,NaN,3.213869,3.958897,-1.586575,-4.658577,NaN,NaN,NaN,2.688102e+09,NaN

In [12]:
wb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3472 entries, 0 to 3471
Data columns (total 16 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   country_name                     3472 non-null   object
 1   country_id                       3472 non-null   object
 2   year                             3472 non-null   int64
 3   Inflation (CPI %)                2694 non-null   float64
 4   GDP (Current USD)                2933 non-null   float64
 5   GDP per Capita (Current USD)     2938 non-null   float64
 6   Unemployment Rate (%)            2795 non-null   float64
 7   Interest Rate (Real, %)          1735 non-null   float64
 8   Inflation (GDP Deflator, %)      2904 non-null   float64
 9   GDP Growth (% Annual)            2912 non-null   float64
 10  Current Account Balance (% GDP)  2563 non-null   float64
 11  Government Expense (% of GDP)    1820 non-null   float64
 12  Government Revenue (% of GDP)    1829 non-null   float64
 13  Tax Revenue (% of GDP)           1833 non-null   float64
 14  Gross National Income (USD)      2796 non-null   float64
 15  Public Debt (% of GDP)           852 non-null    float64
dtypes: float64(13), int64(1), object(2)
memory usage: 434.1+ KB

# Harmoniser les colonnes

Dans WHR :
Country name → majuscule + espace

Dans World Bank :
country_name → minuscule + underscore

In [14]:
whr = whr.rename(columns={"Country name": "Country"})
wb = wb.rename(columns={"country_name": "Country"})
whr = whr.rename(columns={"Year": "year"})

In [15]:
# verification

set(whr["Country"]) - set(wb["Country"])

{'Congo',
 'Côte d’Ivoire',
 'DR Congo',
 'Egypt',
 'Gambia',
 'Hong Kong SAR of China',
 'Iran',
 'Kyrgyzstan',
 'North Cyprus',
 'Republic of Korea',
 'Republic of Moldova',
 'Slovakia',
 'Somaliland Region',
 'State of Palestine',
 'Swaziland',
 'Syria',
 'Taiwan Province of China',
 'Türkiye',
 'Venezuela',
 'Yemen'}

In [16]:
set(wb["Country"]) - set(whr["Country"])

{'American Samoa',
 'Andorra',
 'Antigua and Barbuda',
 'Aruba',
 'Bahamas, The',
 'Barbados',
 'Bermuda',
 'British Virgin Islands',
 'Brunei Darussalam',
 'Cabo Verde',
 'Cayman Islands',
 'Channel Islands',
 'Congo, Dem. Rep.',
 'Congo, Rep.',
 "Cote d'Ivoire",
 'Curacao',
 'Dominica',
 'Egypt, Arab Rep.',
 'Equatorial Guinea',
 'Eritrea',
 'Faroe Islands',
 'Fiji',
 'French Polynesia',
 'Gambia, The',
 'Gibraltar',
 'Greenland',
 'Grenada',
 'Guam',
 'Guinea-Bissau',
 'Hong Kong SAR, China',
 'Iran, Islamic Rep.',
 'Isle of Man',
 'Kiribati',
 "Korea, Dem. People's Rep.",
 'Korea, Rep.',
 'Kyrgyz Republic',
 'Liechtenstein',
 'Macao SAR, China',
 'Marshall Islands',
 'Micronesia, Fed. Sts.',
 'Moldova',
 'Monaco',
 'Nauru',
 'New Caledonia',
 'Northern Mariana Islands',
 'Palau',
 'Papua New Guinea',
 'Samoa',
 'San Marino',
 'Sao Tome and Principe',
 'Seychelles',
 'Sint Maarten (Dutch part)',
 'Slovak Republic',
 'Solomon Islands',
 'St. Kitts and Nevis',
 'St. Lucia',
 'St. Martin (French part)',
 'St. Vincent and the Grenadines',
 'Syrian Arab Republic',
 'Timor-Leste',
 'Tonga',
 'Turkiye',
 'Turks and Caicos Islands',
 'Tuvalu',
 'Vanuatu',
 'Venezuela, RB',
 'Virgin Islands (U.S.)',
 'West Bank and Gaza',
 'Yemen, Rep.'}

In [31]:
# Dictionnaire de correspondance

country_mapping = {
    "Congo": "Congo, Rep.",
    "DR Congo": "Congo, Dem. Rep.",
    "Côte d’Ivoire": "Cote d'Ivoire",
    "Egypt": "Egypt, Arab Rep.",
    "Gambia": "Gambia, The",
    "Hong Kong SAR of China": "Hong Kong SAR, China",
    "Iran": "Iran, Islamic Rep.",
    "Kyrgyzstan": "Kyrgyz Republic",
    "Republic of Korea": "Korea, Rep.",
    "Republic of Moldova": "Moldova",
    "Slovakia": "Slovak Republic",
    "Swaziland": "Eswatini",
    "Venezuela": "Venezuela, RB",
    "Türkiye": "Turkiye",
    "Yemen": "Yemen, Rep.",
    "Taiwan Province of China": None,  # pas dans WB
    "Somaliland Region": None,         # pas dans WB
    "State of Palestine": None,        # pas dans WB
    "North Cyprus": None,              # pas dans WB
    "Syria": None                      # pas dans WB (données manquantes)
}

In [32]:
whr["Country"] = whr["Country"].replace(country_mapping)

In [35]:
whr["Country"] = whr["Country"].replace({
    "Turkey": "Turkiye",
    "Türkiye": "Turkiye"
})

In [36]:
# Vérifier à nouveau les différences

set(whr["Country"]) - set(wb["Country"])

{None}

# Merge de 2 tableaux

In [37]:
merged = pd.merge(
    whr,
    wb,
    on=["Country", "year"],
    how="inner"
)

In [38]:
merged["Country"] = merged["Country"].replace({"Turkiye": "Turkey"})

In [39]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1923 entries, 0 to 1922
Data columns (total 27 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   year                                        1923 non-null   int64
 1   Rank                                        1923 non-null   int64
 2   Country                                     1923 non-null   object
 3   Life evaluation (3-year average)            1923 non-null   float64
 4   Lower whisker                               860 non-null    float64
 5   Upper whisker                               860 non-null    float64
 6   Explained by: Log GDP per capita            858 non-null    float64
 7   Explained by: Social support                858 non-null    float64
 8   Explained by: Healthy life expectancy       858 non-null    float64
 9   Explained by: Freedom to make life choices  857 non-null    float64
 10  Explained by: Generosity                    858 non-null    float64
 11  Explained by: Perceptions of corruption     857 non-null    float64
 12  Dystopia + residual                         856 non-null    float64
 13  country_id                                  1923 non-null   object
 14  Inflation (CPI %)                           1811 non-null   float64
 15  GDP (Current USD)                           1760 non-null   float64
 16  GDP per Capita (Current USD)                1764 non-null   float64
 17  Unemployment Rate (%)                       1906 non-null   float64
 18  Interest Rate (Real, %)                     1068 non-null   float64
 19  Inflation (GDP Deflator, %)                 1758 non-null   float64
 20  GDP Growth (% Annual)                       1758 non-null   float64
 21  Current Account Balance (% GDP)             1674 non-null   float64
 22  Government Expense (% of GDP)               1309 non-null   float64
 23  Government Revenue (% of GDP)               1314 non-null   float64
 24  Tax Revenue (% of GDP)                      1316 non-null   float64
 25  Gross National Income (USD)                 1760 non-null   float64
 26  Public Debt (% of GDP)                      623 non-null    float64
dtypes: float64(23), int64(2), object(2)
memory usage: 405.8+ KB

In [40]:
merged.head()

,year,Rank,Country,Life evaluation (3-year average),Lower whisker,Upper whisker,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,...,Unemployment Rate (%),"Interest Rate (Real, %)","Inflation (GDP Deflator, %)",GDP Growth (% Annual),Current Account Balance (% GDP),Government Expense (% of GDP),Government Revenue (% of GDP),Tax Revenue (% of GDP),Gross National Income (USD),Public Debt (% of GDP)
0,2024,147,Afghanistan,1.364,1.301,1.427,0.649,0.0,0.155,0.0,...,13.295,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023,143,Afghanistan,1.721,1.667,1.775,0.628,0.0,0.242,0.0,...,13.991,NaN,2.961654,2.710887,NaN,NaN,NaN,NaN,1.731538e+10,NaN
2,2022,137,Afghanistan,1.859,1.795,1.923,0.645,0.0,0.087,0.0,...,14.100,NaN,9.406239,-6.240172,NaN,NaN,NaN,NaN,1.454030e+10,NaN
3,2021,146,Afghanistan,2.404,2.339,2.469,0.758,0.0,0.289,0.0,...,11.994,NaN,2.838996,-20.738839,NaN,NaN,NaN,NaN,1.434609e+10,NaN
4,2020,150,Afghanistan,2.523,2.449,2.596,0.370,0.0,0.126,0.0,...,11.710,NaN,6.962946,-2.351101,-15.718303,NaN,NaN,NaN,2.010516e+10,NaN

In [41]:
merged.to_csv("../data/processed/final_dataset.csv", index=False)

In [42]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1923 entries, 0 to 1922
Data columns (total 27 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   year                                        1923 non-null   int64
 1   Rank                                        1923 non-null   int64
 2   Country                                     1923 non-null   object
 3   Life evaluation (3-year average)            1923 non-null   float64
 4   Lower whisker                               860 non-null    float64
 5   Upper whisker                               860 non-null    float64
 6   Explained by: Log GDP per capita            858 non-null    float64
 7   Explained by: Social support                858 non-null    float64
 8   Explained by: Healthy life expectancy       858 non-null    float64
 9   Explained by: Freedom to make life choices  857 non-null    float64
 10  Explained by: Generosity                    858 non-null    float64
 11  Explained by: Perceptions of corruption     857 non-null    float64
 12  Dystopia + residual                         856 non-null    float64
 13  country_id                                  1923 non-null   object
 14  Inflation (CPI %)                           1811 non-null   float64
 15  GDP (Current USD)                           1760 non-null   float64
 16  GDP per Capita (Current USD)                1764 non-null   float64
 17  Unemployment Rate (%)                       1906 non-null   float64
 18  Interest Rate (Real, %)                     1068 non-null   float64
 19  Inflation (GDP Deflator, %)                 1758 non-null   float64
 20  GDP Growth (% Annual)                       1758 non-null   float64
 21  Current Account Balance (% GDP)             1674 non-null   float64
 22  Government Expense (% of GDP)               1309 non-null   float64
 23  Government Revenue (% of GDP)               1314 non-null   float64
 24  Tax Revenue (% of GDP)                      1316 non-null   float64
 25  Gross National Income (USD)                 1760 non-null   float64
 26  Public Debt (% of GDP)                      623 non-null    float64
dtypes: float64(23), int64(2), object(2)
memory usage: 405.8+ KB